reps = [i for i in range(10)]

rule all:
    input:
        # expand("output/ts-{r}.trees", r=reps),
        expand("tmp/base-{r}.txt", r=reps),
        expand("tmp/base_nb-{r}.txt", r=reps),
        expand("tmp/sq-{r}.txt", r=reps),
        expand("tmp/sq_nm-{r}.txt", r=reps),
        expand("tmp/la-{r}.txt", r=reps),
        # expand("tmp/lr-{r}.txt", r=reps),
        "output/mean-times.txt"

rule simulate:
    output:
        # "output/times-sim.txt",
        "output/ts-{r}.trees"
    resources:
        mem_mb=8000,
        runtime=10,
        job_name="ooa-sim",
        output="tmp/sim-{r}.log"
    shell:
        "python simulate-reps.py --rep {wildcards.r}"

rule linkanc:
    input:
        "output/ts-{r}.trees"
    output:
        # "output/times-linkancestors.txt",
        "tmp/la-{r}.txt"
    resources:
        mem_mb=16000,
        runtime=10,
        job_name="ooa-la",
        output="tmp/la-{r}.log"
    shell:
        "python la-time-linkancestors.py --rep {wildcards.r}"

rule baseline:
    input:
        "output/ts-{r}.trees"
    output:
        # "output/times-baseline.txt",
        "tmp/base-{r}.txt"
    resources:
        mem_mb=96000,
        runtime=60,
        job_name="ooa-bs",
        output="tmp/bs-{r}.log"
    shell:
        "python la-time-baseline.py --rep {wildcards.r}"

rule baseline_numba:
    input:
        "output/ts-{r}.trees"
    output:
        # "output/times-baseline.txt",
        "tmp/base_nb-{r}.txt"
    resources:
        mem_mb=128000,
        runtime=60,
        job_name="ooa-bs-nb",
        output="tmp/bs-nb-{r}.log"
    shell:
        "python la-time-baseline-numba.py --rep {wildcards.r}"

rule squash:
    input:
        "output/ts-{r}.trees"
    output:
        # "output/times-squash.txt",
        "tmp/sq-{r}.txt"
    resources:
        mem_mb=8000,
        runtime=900,
        job_name="ooa-sq",
        output="tmp/sq-{r}.log"
    shell:
        "python la-time-squash.py --rep {wildcards.r}"

rule squash_numba:
    input:
        "output/ts-{r}.trees"
    output:
        # "output/times-squash-numba.txt",
        "tmp/sq_nm-{r}.txt"
    resources:
        mem_mb=8000,
        runtime=900,
        job_name="ooa-sq",
        output="tmp/sq_nm-{r}.log"
    shell:
        "python la-time-squash-numba.py --rep {wildcards.r}"

rule stats:
    input:
        [f"tmp/sq-{r}.txt" for r in reps],
        [f"tmp/sq_nm-{r}.txt" for r in reps],
        [f"tmp/base-{r}.txt" for r in reps],
        [f"tmp/base_nb-{r}.txt" for r in reps],
        [f"tmp/la-{r}.txt" for r in reps]
    output:
        "output/mean-times.txt"
    shell:
        "python calculate-means.py"

rule linkanc_recent:
    input:
        "output/ts-{r}.trees"
    output:
        "tmp/lr-{r}.txt"
    resources:
        mem_mb=4000,
        runtime=10,
        job_name="ooa-la-rec",
        output="tmp/lr-{r}.log"
    shell:
        "python la-time-linkancestors-recentadm.py --rep {wildcards.r}"